# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3b8b6c0542614ca367ee2aff35c353a9154a8476bff9e8eab15da29c7dd4cc1b53c38b3789435dca9f473d24240649fd0b163ce6e2b55b0b99fd2fc8a514cc8

test:
  secret_key_base: d0d16eceedb6b410a996e7dce924230f45bf3712a0636fb852423ead57c117628227df9ff1dfe2d51fb402dbe02b353dfafd9ced5afeea5e2c0c70c6de99f949

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
